maximum_length_name: 50
maximum_length_email: 255
max_content: 140
minimum_length_pass: 6
maximum_length_phone: 15
size_gravatar: 80
subjects_per_page: 12
users_per_page: 12
questions_per_page: 15
exams_per_page: 15
maximum_length_question_content: 400
maximum_length_subject_name: 20 
remaining_time: 3600
hours: 3600
minutes: 60
questions: 10
one: 1
trainee_exams_per_page: 15
zero: 0
factories:
  question:
    supervisor_id: 1
  exam:
    time_limit: 10
    pass_score: 3
    total_score: 6
    number_question: 3
    name_max_length: 50
    name_invalid_length: 51
  user:
    supervisor_role: 0
    trainee_role: 1
    phone_length: 11
    pass_length: 8

